### ISSUE TITLE
Dear author, when I was runing this project in release mode, the backend have some problem 

### ISSUE THREAD

**Issue by Inuniverse** [BerwinZ/RGBD_VisualOdometry#7]
Image #3
Frontend status: Tracking
Corase computing...
Minimum distance of matches 3
Largest distance of matches 30
  Size of tracking map: 425
  Size of mappoint candidates: 425
  Size of matched <mappoint, keypoint> pairs: 226
  PNP results inlier size: 207
got outliders after first round BA: 80
Fine computing...
Minimum distance of matches 3
Largest distance of matches 30
  Size of tracking map: 425
  Size of mappoint candidates: 425
  Size of matched <mappoint, keypoint> pairs: 226
  PNP results inlier size: 207
got outliders after first round BA: 80
Current frame is a new keyframe
Created new mappoints: 229
 for keyframe 1 add 24 new observations 
 for keyframe 4 add 229 new observations 
  Triangulate active mappoints size: 1

Backend starts optimization

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

May I ask how could I fix it? Thank you

**Comment by BowenBZ** [comment]
Could you provide which dataset you're running?

**Comment by BowenBZ** [comment]
Looks like the -O3 compile in the release build exposes some implicit bugs. Fixing the compile warnings (#10) resolved the crash on my end. Not sure whether it applies to you.
