### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by Rocky-YU** [BerwinZ/RGBD_VisualOdometry#8]
Hey, thanks for your work, but I'm having the following problem with the compilation process.

/usr/bin/ld: 找不到 -lglut
collect2: error: ld returned 1 exit status
src/CMakeFiles/myslam.dir/build.make:238: recipe for target '../lib/libmyslam.so' failed

**Comment by BowenBZ** [comment]
Could you try to run the command
```
sudo apt-get install freeglut3-dev 
```
Then recompile the project.

Looks like there are some dependencies not installed properly. You could refer to [docker/DockerFile](https://github.com/BowenBZ/RGBD_VisualOdometry/blob/master/docker/Dockerfile) for full dependency setup.

**Comment by Rocky-YU** [comment]
Thank you very much for response. They are indeed workable and helpful. Thank you once again!
